app = "coral-deb-app"
primary_region = "sjc"  # or a region near you

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 1

  [http_service.concurrency]
    type = "requests"
    soft_limit = 10
    hard_limit = 15
